//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MujiStore.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class tblDeploySchedule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblDeploySchedule()
        {
            this.tblStreamServers = new HashSet<tblStreamServer>();
        }

        public int DeployScheduleID { get; set; }

        [Required(ErrorMessageResourceType = typeof(MujiStore.Resources.Resource), ErrorMessageResourceName = nameof(MujiStore.Resources.Resource.ModtblEnterDeployNameDataAnnaValida1))]
        [MaxLength(60, ErrorMessageResourceType = typeof(MujiStore.Resources.Resource), ErrorMessageResourceName = nameof(MujiStore.Resources.Resource.ModtblMaxLengthDataAnnaValida1))]
        [Display(Name = nameof(MujiStore.Resources.Resource.CntDeployScheduleName), ResourceType = typeof(MujiStore.Resources.Resource))]
        public string Name { get; set; }
        [Required(ErrorMessageResourceType = typeof(MujiStore.Resources.Resource), ErrorMessageResourceName = nameof(MujiStore.Resources.Resource.ModtblDeployScheduleDataAnnaValida1))]
        [MaxLength(500, ErrorMessageResourceType = typeof(MujiStore.Resources.Resource), ErrorMessageResourceName = nameof(MujiStore.Resources.Resource.ModtblMaxLengthDataAnnaValida2))]
        [Display(Name = nameof(MujiStore.Resources.Resource.CntDeploySchedule), ResourceType = typeof(MujiStore.Resources.Resource))]
        public string Schedule { get; set; }

        [Display(Name = nameof(MujiStore.Resources.Resource.CntDeployeDeleteFlag), ResourceType = typeof(MujiStore.Resources.Resource))]
        public bool DELFG { get; set; }
        public Nullable<System.DateTime> CRTDT { get; set; }
        public string CRTCD { get; set; }
        public Nullable<System.DateTime> UPDDT { get; set; }
        public string UPDCD { get; set; }
        public string IPAddress { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblStreamServer> tblStreamServers { get; set; }
    }
}
