//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MujiStore.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class tblFormat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblFormat()
        {
            this.tblDeployStatus = new HashSet<tblDeployStatu>();
        }

        public int FormatID { get; set; }

        [Required(ErrorMessage = nameof(MujiStore.Resources.Resource.TblFormatEnterNameFormat))]
        [Display(Name = nameof(MujiStore.Resources.Resource.TblFormatName), ResourceType = typeof(MujiStore.Resources.Resource))]

        public string Name { get; set; }

        [Required(ErrorMessage = nameof(MujiStore.Resources.Resource.TblFormatRequiredBandWidth))]
        [Display(Name = nameof(MujiStore.Resources.Resource.TblFormatRequiredBandWidth1), ResourceType = typeof(MujiStore.Resources.Resource))]
        [Range(1000, 60000, ErrorMessageResourceType = typeof(MujiStore.Resources.Resource), ErrorMessageResourceName = nameof(MujiStore.Resources.Resource.TblFormatRequiredBandWidth2))]
        public Nullable<float> RequiredBandWidth { get; set; }

        [Display(Name = nameof(MujiStore.Resources.Resource.TblFormatDELFG), ResourceType = typeof(MujiStore.Resources.Resource))]
        public bool DELFG { get; set; }
        public Nullable<System.DateTime> CRTDT { get; set; }
        public string CRTCD { get; set; }
        public Nullable<System.DateTime> UPDDT { get; set; }
        public string UPDCD { get; set; }
        public string IPAddress { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDeployStatu> tblDeployStatus { get; set; }
    }
}
