//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MujiStore.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;
    using System.ComponentModel.DataAnnotations;

    public partial class tblFeedback
    {

        [Display(Name = nameof(MujiStore.Resources.Resource.FeedbackID), ResourceType = typeof(MujiStore.Resources.Resource))]
        public int FeedbackID { get; set; }
        [Display(Name = nameof(MujiStore.Resources.Resource.ModFeedbackMovieID), ResourceType = typeof(MujiStore.Resources.Resource))]
        public int MovieID { get; set; }

        //"Writer Name
        [Display(Name = nameof(MujiStore.Resources.Resource.ModFeedbackWriterName), ResourceType = typeof(MujiStore.Resources.Resource))]
        [Required(ErrorMessageResourceType = typeof(MujiStore.Resources.Resource), ErrorMessageResourceName = nameof(MujiStore.Resources.Resource.ModFeedbackDataAnnaValida1))]
        public string WriterName { get; set; }

        //Comments
        [Display(Name = nameof(MujiStore.Resources.Resource.ModFeedbackComments), ResourceType = typeof(MujiStore.Resources.Resource))]
        [Required(ErrorMessageResourceType = typeof(MujiStore.Resources.Resource), ErrorMessageResourceName = nameof(MujiStore.Resources.Resource.ModFeedbackDataAnnaValida2))]
        public string Comments { get; set; }

        [Display(Name = nameof(MujiStore.Resources.Resource.CommonFileName), ResourceType = typeof(MujiStore.Resources.Resource))]
        public string FileName { get; set; }

        [Display(Name = nameof(MujiStore.Resources.Resource.CommonIpAddress), ResourceType = typeof(MujiStore.Resources.Resource))]
        public string IPAddress { get; set; }

        [Display(Name = nameof(MujiStore.Resources.Resource.ModFeedbackWriterDatetime), ResourceType = typeof(MujiStore.Resources.Resource))]
        public System.DateTime WriterDatetime { get; set; }

        [Display(Name = nameof(MujiStore.Resources.Resource.CommonDELFG), ResourceType = typeof(MujiStore.Resources.Resource))]
        public bool DELFG { get; set; }

        [Display(Name = nameof(MujiStore.Resources.Resource.CommonCRTDT), ResourceType = typeof(MujiStore.Resources.Resource))]
        public System.DateTime CRTDT { get; set; }

        [Display(Name = nameof(MujiStore.Resources.Resource.CommonCRTCD), ResourceType = typeof(MujiStore.Resources.Resource))]
        public string CRTCD { get; set; }

        [Display(Name = nameof(MujiStore.Resources.Resource.CommonUPDDT), ResourceType = typeof(MujiStore.Resources.Resource))]
        public Nullable<System.DateTime> UPDDT { get; set; }

        [Display(Name = nameof(MujiStore.Resources.Resource.CommonUPDCD), ResourceType = typeof(MujiStore.Resources.Resource))]
        public string UPDCD { get; set; }

        [Display(Name = nameof(MujiStore.Resources.Resource.FolderId), ResourceType = typeof(MujiStore.Resources.Resource))]
        public int FolderID { get; set; }
      //  [RegularExpression(@"([a-zA-Z0-9\s_\\.\-:])+(.png|.jpg|.gif|.Png|.pNg|.pnG|.PNg|.pNG|.PnG|.PNG|.Jpg|.jPg|.jpG|.JPg|.jPG|.JpG|.JPG|.Gif|.gIf|.giF|.GIf|.gIF|.GiF|.GIF)$", ErrorMessage = nameof(MujiStore.Resources.Resource.ModFeedbackDataAnnaValida3), ErrorMessageResourceType = typeof(MujiStore.Resources.Resource))]
        public HttpPostedFileBase PostedFile { get; set; }

        [Display(Name = nameof(MujiStore.Resources.Resource.ModFeedbackMediaTitle), ResourceType = typeof(MujiStore.Resources.Resource))]
        public string MediaTitle { get; set; }

        [Display(Name = nameof(MujiStore.Resources.Resource.ModFeedbackMediaDescription), ResourceType = typeof(MujiStore.Resources.Resource))]
        public string MediaDescription { get; set; }

        [Display(Name = nameof(MujiStore.Resources.Resource.ModFeedbackMediaFileName), ResourceType = typeof(MujiStore.Resources.Resource))]
        public string MediaFileName { get; set; }

        [Display(Name = nameof(MujiStore.Resources.Resource.ModFeedbackMediaFolderName), ResourceType = typeof(MujiStore.Resources.Resource))]
        public string MediaFolderName { get; set; }

        public virtual tblMedia tblMedia { get; set; }
    }
}
