//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MujiStore.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblStreamServer
    {
        public int StreamServerID { get; set; }

        [Required(ErrorMessageResourceType = typeof(MujiStore.Resources.Resource), ErrorMessageResourceName = nameof(MujiStore.Resources.Resource.ModtblStreamServerNameDataAnnaValida1))]
        [MaxLength(60, ErrorMessageResourceType = typeof(MujiStore.Resources.Resource), ErrorMessageResourceName = nameof(MujiStore.Resources.Resource.ModtblStreamServerMaxLenDataAnnaValida2))]
        [Display(Name = nameof(MujiStore.Resources.Resource.TblStreamSreverName), ResourceType = typeof(MujiStore.Resources.Resource))]
        public string SSServer { get; set; }
        [Required(ErrorMessageResourceType = typeof(MujiStore.Resources.Resource), ErrorMessageResourceName = nameof(MujiStore.Resources.Resource.ModtblEnterIpAddressDataAnnaValida1))]
        [MaxLength(15, ErrorMessageResourceType = typeof(MujiStore.Resources.Resource), ErrorMessageResourceName = nameof(MujiStore.Resources.Resource.ModtblStreamServerMaxLenCharDataAnnaValida2))]
        [RegularExpression(@"^([1-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])(\.([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])){3}$", ErrorMessageResourceType = typeof(MujiStore.Resources.Resource), ErrorMessageResourceName = nameof(MujiStore.Resources.Resource.ModtblSubnetSNIPAddressDataAnnaValida2))]
        [Display(Name = nameof(MujiStore.Resources.Resource.TblStreamSreverIpAddress), ResourceType = typeof(MujiStore.Resources.Resource))]

        public string IPAddress { get; set; }

        [Required(ErrorMessageResourceType = typeof(MujiStore.Resources.Resource), ErrorMessageResourceName = nameof(MujiStore.Resources.Resource.ModtblSelectIpAddressDataAnnaValida1))]
        [Display(Name = nameof(MujiStore.Resources.Resource.TblSubnet), ResourceType = typeof(MujiStore.Resources.Resource))]

        public Nullable<int> BelongingSubnet { get; set; }
        [Required(ErrorMessageResourceType = typeof(MujiStore.Resources.Resource), ErrorMessageResourceName = nameof(MujiStore.Resources.Resource.ModtblSelectDeployeScheduleDataAnnaValida1))]
        [Display(Name = nameof(MujiStore.Resources.Resource.TblDeploySchedule), ResourceType = typeof(MujiStore.Resources.Resource))]

        public Nullable<int> DeploySchedule { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> LastDeployDate { get; set; }
        public Nullable<long> LastStatusCheckDateDatetime { get; set; }

        [Range(0, int.MaxValue, ErrorMessageResourceType = typeof(MujiStore.Resources.Resource), ErrorMessageResourceName = nameof(MujiStore.Resources.Resource.ModtblDriverCTotalDataAnnaValida2))]
        [Display(Name = nameof(MujiStore.Resources.Resource.TblDriverCCount), ResourceType = typeof(MujiStore.Resources.Resource))]

        public Nullable<long> DriveCTotal { get; set; }
        [Range(0, int.MaxValue, ErrorMessageResourceType = typeof(MujiStore.Resources.Resource), ErrorMessageResourceName = nameof(MujiStore.Resources.Resource.ModtblEnterValidDriverCFreeDataAnnaValida2))]
        [Display(Name = nameof(MujiStore.Resources.Resource.TblDriverCFree), ResourceType = typeof(MujiStore.Resources.Resource))]

        public Nullable<long> DriveCFree { get; set; }

        [Range(0, int.MaxValue, ErrorMessageResourceType = typeof(MujiStore.Resources.Resource), ErrorMessageResourceName = nameof(MujiStore.Resources.Resource.ModtblValidDriverDTotalDataAnnaValida2))]

        [Display(Name = nameof(MujiStore.Resources.Resource.TblDriverDTotal), ResourceType = typeof(MujiStore.Resources.Resource))]

        public Nullable<long> DriveDTotal { get; set; }


        [Range(0, int.MaxValue, ErrorMessageResourceType = typeof(MujiStore.Resources.Resource), ErrorMessageResourceName = nameof(MujiStore.Resources.Resource.ModtblDriveDFreeDataAnnaValida2))]
        [Display(Name = nameof(MujiStore.Resources.Resource.TblDriveDFree), ResourceType = typeof(MujiStore.Resources.Resource))]

        public Nullable<long> DriveDFree { get; set; }
        [Display(Name = nameof(MujiStore.Resources.Resource.CommonDelFlg), ResourceType = typeof(MujiStore.Resources.Resource))]
        public bool DELFG { get; set; }
        public Nullable<System.DateTime> CRTDT { get; set; }
        public string CRTCD { get; set; }
        public Nullable<System.DateTime> UPDDT { get; set; }
        public string UPDCD { get; set; }
        public string UserIPAddress { get; set; }


        [Display(Name = nameof(MujiStore.Resources.Resource.TblSubnetName), ResourceType = typeof(MujiStore.Resources.Resource))]

        public string SubNetName { get; set; }

        [Display(Name = nameof(MujiStore.Resources.Resource.TblDeployScheduleName), ResourceType = typeof(MujiStore.Resources.Resource))]

        public string DeployScheduleName { get; set; }

        [Display(Name = nameof(MujiStore.Resources.Resource.TblDriveCTotal), ResourceType = typeof(MujiStore.Resources.Resource))]

        public string DVCTotal { get; set; }

        [Display(Name = nameof(MujiStore.Resources.Resource.TblDriveCFree), ResourceType = typeof(MujiStore.Resources.Resource))]

        public string DVCFree { get; set; }

        [Display(Name = nameof(MujiStore.Resources.Resource.TblDriveDTotal), ResourceType = typeof(MujiStore.Resources.Resource))]

        public string DVDTotal { get; set; }

        [Display(Name = nameof(MujiStore.Resources.Resource.TblDriveDFree1), ResourceType = typeof(MujiStore.Resources.Resource))]

        public string DVDFree { get; set; }

        public long NotExistsMediaCount { get; set; }
        public long ExistsMediaCount { get; set; }
        public long NotExistsFileSize { get; set; }
        public long ExistsFileSize { get; set; }
        public int StoreID { get; set; }
        public string StoreName { get; set; }
        public string StoreGroupName { get; set; }
        public int StoreGroupID { get; set; }
       

        public virtual tblDeploySchedule tblDeploySchedule { get; set; }
        public virtual tblSubnet tblSubnet { get; set; }

        public string OrigSSServer { get; set; }
        public Nullable<int> FormatID { get; set; }
    }
}
