//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MujiStore.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblStoreGroupFolder
    {
        public int StoreGroupFolderID { get; set; }
        [Display(Name = nameof(MujiStore.Resources.Resource.ModtblStoreGroupFolderStoreGroupID), ResourceType = typeof(MujiStore.Resources.Resource))]
        public Nullable<int> StoreGroupID { get; set; }

        [Display(Name = nameof(MujiStore.Resources.Resource.ModtblStoreGroupFolderFolderID), ResourceType = typeof(MujiStore.Resources.Resource))]
        public Nullable<int> FolderID { get; set; }

        [Display(Name = nameof(MujiStore.Resources.Resource.CommonDelFlg), ResourceType = typeof(MujiStore.Resources.Resource))]
        public bool DELFG { get; set; }

        public Nullable<System.DateTime> CRTDT { get; set; }
        public string CRTCD { get; set; }
        public Nullable<System.DateTime> UPDDT { get; set; }
        public string UPDCD { get; set; }
        public string IPAddress { get; set; }
    
        public virtual tblFolder tblFolder { get; set; }
        public virtual tblStoreGroup tblStoreGroup { get; set; }
    }
}
