//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MujiStore.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblStreamServerSubnet
    {
        public int StreamServerSubnetID { get; set; }
        [Required(ErrorMessageResourceType = typeof(MujiStore.Resources.Resource), ErrorMessageResourceName = nameof(MujiStore.Resources.Resource.ModtblMediaStreamServerNameDataAnnaValida1))]
        [MaxLength(60, ErrorMessageResourceType = typeof(MujiStore.Resources.Resource), ErrorMessageResourceName = nameof(MujiStore.Resources.Resource.ModtblMediaStreamServerMaxLenDataAnnaValida2))]
        [Display(Name = nameof(MujiStore.Resources.Resource.ModtblMediaStreamServerName), ResourceType = typeof(MujiStore.Resources.Resource))]
        public string SSSServer { get; set; }
        [Required(ErrorMessageResourceType = typeof(MujiStore.Resources.Resource), ErrorMessageResourceName = nameof(MujiStore.Resources.Resource.ModtblMediaSelectSubnetDataAnnaValida))]
        [Display(Name = nameof(MujiStore.Resources.Resource.ModtblMediaSubnet), ResourceType = typeof(MujiStore.Resources.Resource))]
        public Nullable<int> Subnet { get; set; }
        public Nullable<int> FormatID { get; set; }
        [Display(Name = nameof(MujiStore.Resources.Resource.CommonDelFlg), ResourceType = typeof(MujiStore.Resources.Resource))]
        public bool DELFG { get; set; }
        public Nullable<System.DateTime> CRTDT { get; set; }
        public string CRTCD { get; set; }
        public Nullable<System.DateTime> UPDDT { get; set; }
        public string UPDCD { get; set; }
        public string IPAddress { get; set; }
    
        public virtual tblSubnet tblSubnet { get; set; }
    }
}
