//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MujiStore.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblSubnet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblSubnet()
        {
            this.tblStoreSubnets = new HashSet<tblStoreSubnet>();
            this.tblStreamServers = new HashSet<tblStreamServer>();
            this.tblStreamServerSubnets = new HashSet<tblStreamServerSubnet>();
        }

        public int SubnetID { get; set; }

        [Display(Name = nameof(MujiStore.Resources.Resource.ModtblSubnetSNIPAddres), ResourceType = typeof(MujiStore.Resources.Resource))]
        [Required(ErrorMessageResourceType = typeof(MujiStore.Resources.Resource), ErrorMessageResourceName = nameof(MujiStore.Resources.Resource.ModtblSubnetSNIPAddressDataAnnaValida1))]
        [RegularExpression(@"^([1-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])(\.([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])){3}$", ErrorMessageResourceType = typeof(MujiStore.Resources.Resource), ErrorMessageResourceName = nameof(MujiStore.Resources.Resource.ModtblSubnetSNIPAddressDataAnnaValida2))]
        public string SNIPAddress { get; set; }

        [Display(Name = nameof(MujiStore.Resources.Resource.ModtblSubnetSubMask), ResourceType = typeof(MujiStore.Resources.Resource))]
        [Required(ErrorMessageResourceType = typeof(MujiStore.Resources.Resource), ErrorMessageResourceName = nameof(MujiStore.Resources.Resource.ModtblSubnetSubMaskDataAnnaValida1))]
        [RegularExpression(@"^([1-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])(\.([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])){3}$", ErrorMessageResourceType = typeof(MujiStore.Resources.Resource), ErrorMessageResourceName = nameof(MujiStore.Resources.Resource.ModtblSubnetSubMaskDataAnnaValida2))]
        public string SubnetMask { get; set; }


        [Display(Name = nameof(MujiStore.Resources.Resource.ModtblSubnetWANBandW), ResourceType = typeof(MujiStore.Resources.Resource))]
        [Required(ErrorMessageResourceType = typeof(MujiStore.Resources.Resource), ErrorMessageResourceName = nameof(MujiStore.Resources.Resource.ModtblSubnetWANBandWDataAnnaValida1))]
        [Range(1000, 50000, ErrorMessageResourceType = typeof(MujiStore.Resources.Resource), ErrorMessageResourceName = nameof(MujiStore.Resources.Resource.ModtblSubnetWANBandWDataAnnaValida2))]
        public double WANBandWidth { get; set; }


        [Display(Name = nameof(MujiStore.Resources.Resource.ModtblSubnetLANBandW), ResourceType = typeof(MujiStore.Resources.Resource))]
        [Required(ErrorMessageResourceType = typeof(MujiStore.Resources.Resource), ErrorMessageResourceName = nameof(MujiStore.Resources.Resource.ModtblSubnetLANBandWDataAnnaValida1))]
        [Range(1000, 50000, ErrorMessageResourceType = typeof(MujiStore.Resources.Resource), ErrorMessageResourceName = nameof(MujiStore.Resources.Resource.ModtblSubnetLANBandWDataAnnaValida2))]
        public double LANBandWidth { get; set; }

        [Display(Name = nameof(MujiStore.Resources.Resource.CommonDelFlg), ResourceType = typeof(MujiStore.Resources.Resource))]
        public bool DELFG { get; set; }
        public Nullable<System.DateTime> CRTDT { get; set; }
        public string CRTCD { get; set; }
        public Nullable<System.DateTime> UPDDT { get; set; }
        public string UPDCD { get; set; }
        public string IPAddress { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblStoreSubnet> tblStoreSubnets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblStreamServer> tblStreamServers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblStreamServerSubnet> tblStreamServerSubnets { get; set; }
    }
}
