//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MujiStore.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;


    public partial class tblUser
    {
        [Display(Name = nameof(MujiStore.Resources.Resource.userid), ResourceType = typeof(MujiStore.Resources.Resource))]
        public int UserID { get; set; }

        [Required(ErrorMessageResourceType = typeof(MujiStore.Resources.Resource), ErrorMessageResourceName = nameof(MujiStore.Resources.Resource.ModtblUserUserNameDataAnnaValida1))]
        [MaxLength(25, ErrorMessageResourceType = typeof(MujiStore.Resources.Resource), ErrorMessageResourceName = nameof(MujiStore.Resources.Resource.CommonDataAnna0of1))]
        [Display(Name = nameof(MujiStore.Resources.Resource.ModtblUserUserName), ResourceType = typeof(MujiStore.Resources.Resource))]
        public string UserName { get; set; }

        [Required(ErrorMessageResourceType = typeof(MujiStore.Resources.Resource), ErrorMessageResourceName = nameof(MujiStore.Resources.Resource.ModtblUserUserEmailDataAnnaValida1))]
        [MaxLength(25, ErrorMessageResourceType = typeof(MujiStore.Resources.Resource), ErrorMessageResourceName = nameof(MujiStore.Resources.Resource.CommonDataAnna0of1))]
        [Display(Name = nameof(MujiStore.Resources.Resource.ModtblUserUserEmail), ResourceType = typeof(MujiStore.Resources.Resource))]
        [RegularExpression("^[a-zA-Z0-9_\\.-]+@([a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,6}$", ErrorMessageResourceType = typeof(MujiStore.Resources.Resource), ErrorMessageResourceName = nameof(MujiStore.Resources.Resource.ModtblUserUserEmailDataAnnaValida3))]
        public string UserEmail { get; set; }


        [Required(ErrorMessageResourceType = typeof(MujiStore.Resources.Resource), ErrorMessageResourceName = nameof(MujiStore.Resources.Resource.ModtblUserPasswordDataAnnaValida1))]
        [MaxLength(25, ErrorMessageResourceType = typeof(MujiStore.Resources.Resource), ErrorMessageResourceName = nameof(MujiStore.Resources.Resource.CommonDataAnna0of1))]
        [Display(Name = nameof(MujiStore.Resources.Resource.ModtblUserPassword), ResourceType = typeof(MujiStore.Resources.Resource))]
        public string Password { get; set; }

        public string Role { get; set; }

        [Display(Name = nameof(MujiStore.Resources.Resource.CommonDelFlg), ResourceType = typeof(MujiStore.Resources.Resource))]
        public bool DELFG { get; set; }

        [Display(Name = nameof(MujiStore.Resources.Resource.CommonCRTDT), ResourceType = typeof(MujiStore.Resources.Resource))]
        public Nullable<System.DateTime> CRTDT { get; set; }

        [Display(Name = nameof(MujiStore.Resources.Resource.CommonCRTCD), ResourceType = typeof(MujiStore.Resources.Resource))]
        public string CRTCD { get; set; }

        [Display(Name = nameof(MujiStore.Resources.Resource.CommonUPDDT), ResourceType = typeof(MujiStore.Resources.Resource))]
        public Nullable<System.DateTime> UPDDT { get; set; }

        [Display(Name = nameof(MujiStore.Resources.Resource.CommonUPDCD), ResourceType = typeof(MujiStore.Resources.Resource))]
        public string UPDCD { get; set; }

        [Display(Name = nameof(MujiStore.Resources.Resource.CommonIpAddress), ResourceType = typeof(MujiStore.Resources.Resource))]
        public string IPAddress { get; set; }
        public int Authority { get; set; }
        public bool Authority1 { get; set; }
        public bool Authority2 { get; set; }
        public bool Authority4 { get; set; }
        public bool Authority8 { get; set; }
        public bool Authority16 { get; set; }

        [Display(Name = nameof(MujiStore.Resources.Resource.ModtblUserOldPassword), ResourceType = typeof(MujiStore.Resources.Resource))]
        [Required(ErrorMessageResourceType = typeof(MujiStore.Resources.Resource), ErrorMessageResourceName = nameof(MujiStore.Resources.Resource.ModtblUserOldPasswordDataAnnaValida1))]
        [MaxLength(25, ErrorMessageResourceType = typeof(MujiStore.Resources.Resource), ErrorMessageResourceName = nameof(MujiStore.Resources.Resource.CommonDataAnna0of1))]
        public string OldPassword { get; set; }

        [Display(Name = nameof(MujiStore.Resources.Resource.ModtblUserNewPassword), ResourceType = typeof(MujiStore.Resources.Resource))]
        [Required(ErrorMessageResourceType = typeof(MujiStore.Resources.Resource), ErrorMessageResourceName = nameof(MujiStore.Resources.Resource.ModtblUserNewPasswordDataAnnaValida1))]
        [MaxLength(25, ErrorMessageResourceType = typeof(MujiStore.Resources.Resource), ErrorMessageResourceName = nameof(MujiStore.Resources.Resource.CommonDataAnna0of1))]
        public string NewPassword { get; set; }

        [Display(Name = nameof(MujiStore.Resources.Resource.ModtblUserConfirmNewPassword), ResourceType = typeof(MujiStore.Resources.Resource))]
        [Required(ErrorMessageResourceType = typeof(MujiStore.Resources.Resource), ErrorMessageResourceName = nameof(MujiStore.Resources.Resource.ModtblUserConfirmPasswordDataAnnaValida1))]
        [MaxLength(25, ErrorMessageResourceType = typeof(MujiStore.Resources.Resource), ErrorMessageResourceName = nameof(MujiStore.Resources.Resource.CommonDataAnna0of1))]
        public string ConfirmNewPassword { get; set; }

        public string RoleName { get; set; }
    }
}
